services:
  - type: web
    name: ecotrace-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app -w 2 -b 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:////opt/render/project/src/ecotrace.db
