import io, csv
from datetime import date, timedelta
from flask import Blueprint, Response, request
from app.db import fetchall, fetchone
from app.utils.jwt_utils import jwt_required, get_jwt_identity
from app.services.score_engine import compute_score
from app.services.analytics_service import get_analytics
from app.utils.helpers import success, error

reports_bp = Blueprint("reports", __name__)


@reports_bp.get("/csv")
@jwt_required()
def export_csv():
    uid   = get_jwt_identity()
    days  = int(request.args.get("days", 30))
    since = (date.today() - timedelta(days=days)).isoformat()
    rows  = fetchall(
        "SELECT * FROM carbon_records WHERE user_id=? AND date>=? ORDER BY date",
        (uid, since)
    )
    out = io.StringIO()
    w   = csv.writer(out)
    w.writerow(["Date","Transport(kg)","Electricity(kg)","Food(kg)","Fuel(kg)","Total(kg)","Food Type"])
    for r in rows:
        w.writerow([r["date"], r["transport_emissions"], r["electricity_emissions"],
                    r["food_emissions"], r["fuel_emissions"], r["total_emissions"], r["food_type"]])
    out.seek(0)
    return Response(
        out.getvalue(), mimetype="text/csv",
        headers={"Content-Disposition":
                 f"attachment; filename=ecotrace_{uid}_{date.today()}.csv"}
    )


@reports_bp.get("/pdf")
@jwt_required()
def export_pdf():
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib.units import cm
    except ImportError:
        return error("reportlab not installed. Run: pip install reportlab", 500)

    uid   = get_jwt_identity()
    user  = fetchone("SELECT * FROM users WHERE id=?", (uid,))
    days  = int(request.args.get("days", 30))
    since = (date.today() - timedelta(days=days)).isoformat()
    rows  = fetchall(
        "SELECT * FROM carbon_records WHERE user_id=? AND date>=? ORDER BY date",
        (uid, since)
    )
    score = compute_score(uid)

    buf    = io.BytesIO()
    doc    = SimpleDocTemplate(buf, pagesize=A4, topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    GREEN  = colors.HexColor("#00c896")
    elems  = []

    elems.append(Paragraph(
        "<b><font color='#00c896'>EcoTrace</font> — Carbon Footprint Report</b>",
        styles["Title"]))
    elems.append(Paragraph(
        f"User: {user['name']}  |  Period: last {days} days  |  Generated: {date.today()}",
        styles["Normal"]))
    elems.append(Spacer(1, 0.5*cm))
    elems.append(Paragraph(
        f"<b>Sustainability Score: {score['score']}/100 "
        f"({score['grade']} — {score['label']})</b>", styles["Heading2"]))
    elems.append(Spacer(1, 0.4*cm))

    if rows:
        total_kg = sum(r["total_emissions"] for r in rows)
        elems.append(Paragraph(
            f"<b>Total emissions ({days} days):</b> {total_kg:.3f} kg CO₂e",
            styles["Normal"]))
        elems.append(Spacer(1, 0.5*cm))

        tdata = [["Date","Transport","Electricity","Food","Fuel","Total (kg)"]]
        for r in rows:
            tdata.append([
                r["date"],
                f"{r['transport_emissions']:.3f}",
                f"{r['electricity_emissions']:.3f}",
                f"{r['food_emissions']:.3f}",
                f"{r['fuel_emissions']:.3f}",
                f"{r['total_emissions']:.3f}",
            ])
        t = Table(tdata, repeatRows=1)
        t.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,0), GREEN),
            ("TEXTCOLOR",  (0,0), (-1,0), colors.white),
            ("FONTNAME",   (0,0), (-1,0), "Helvetica-Bold"),
            ("FONTSIZE",   (0,0), (-1,-1), 8),
            ("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.white, colors.HexColor("#f0fdf8")]),
            ("GRID",       (0,0), (-1,-1), 0.5, colors.HexColor("#cccccc")),
            ("ALIGN",      (1,0), (-1,-1), "CENTER"),
        ]))
        elems.append(t)
    else:
        elems.append(Paragraph("No records in this period.", styles["Normal"]))

    elems.append(Spacer(1, 1*cm))
    elems.append(Paragraph(
        "<i>Generated by EcoTrace — Carbon Footprint Awareness Platform</i>",
        styles["Normal"]))

    doc.build(elems)
    buf.seek(0)
    return Response(
        buf.getvalue(), mimetype="application/pdf",
        headers={"Content-Disposition":
                 f"attachment; filename=ecotrace_report_{uid}_{date.today()}.pdf"}
    )


@reports_bp.get("/summary")
@jwt_required()
def summary():
    return success(get_analytics(get_jwt_identity()))
